get http://localhost:3000/agenda/
###

post http://localhost:3000/todos/ 


    {
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}
```


###

put http://localhost:3000/todos/6/ 
Content-Type: {application/json}
    {
      "status": "DONE"
    }

###

DELETE http://localhost:3000/todos/4/ 



